# Generated by Django 5.0.4 on 2024-06-28 08:01

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="last_sent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 8, 1, 43, 738710, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 8, 1, 43, 739167, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
