# Generated by Django 5.0.4 on 2024-07-12 10:01

import datetime

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alter_city_id_alter_subscription_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="country_abbr",
            field=models.CharField(
                max_length=4, verbose_name="country abbreviation"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50, verbose_name="city name"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="last_sent",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 12, 10, 1, 26, 895452, tzinfo=datetime.timezone.utc
                ),
                verbose_name="last sent",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="last_update",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 12, 10, 1, 26, 896147, tzinfo=datetime.timezone.utc
                ),
                verbose_name="last update",
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="weather_description",
            field=models.CharField(
                max_length=100, verbose_name="weather description"
            ),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="weather_icon",
            field=models.CharField(max_length=4, verbose_name="weather icon"),
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="wind_speed",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="wind speed"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["last_sent"], name="weather_sub_last_se_d0bda1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user"], name="weather_sub_user_id_8dfa68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["city"], name="weather_sub_city_id_a521c5_idx"
            ),
        ),
    ]
